---
- hosts: localhost
  become: true
  tasks:
  - maven_artifact:
     group_id: doc-examples
     artifact_id: lambda-java-example
     version: 1.1
     repository_url: 'https://nexus.induseoffice.com/repository/maven-releases/'
     dest: /tmp/
