---
- hosts: tomcat
  become: true
  tasks:
  - maven_artifact:
     group_id: doc-examples
     artifact_id: lambda-java-example
     version: 1.1
     repository_url: 'http://54.196.0.219:8081/repository/maven-releases/'
     username: admin
     password: admin123
     dest: /tmp/
